### ISSUE TITLE
Change the css for tex logo

### ISSUE THREAD

**Issue by SwitWu** [DominikPeters/pgf-tikz-html-manual#6]
### Brief outline of the proposed feature

I'd suggest to change the css for tex logos into the following code:
```css
/* tex and latex logo */

.latexlogosup {
  text-transform: uppercase;
  font-size: 70%;
  font-weight: 500;
  margin-left: -.45em;
  margin-right: -.15em;
  position: relative;
  bottom: .62ex;
}

.latexlogosub {
  text-transform: uppercase;
  margin-left: -0.18em;
  margin-right: -0.05em;
  bottom: -0.5ex;
  position: relative;
}
```
For its effect, see this screenshot:
<img width="1021" alt="image" src="https://github.com/DominikPeters/pgf-tikz-html-manual/assets/39337667/69951509-a698-41e9-b058-87e168c09910">
